### ISSUE TITLE
Change Editor Tab color depending of file path

### ISSUE THREAD

**Issue by sdavidg** [iloveeclipse/skin4eclipse#18]
Is it possible to do this?

![colortabs](https://cloud.githubusercontent.com/assets/4955944/14559556/e3e94d32-0309-11e6-91a4-a8853b07edcb.png)

For reference: http://stackoverflow.com/questions/11614020/eclipse-plugin-change-editor-tab-color-depending-of-file-path

**Comment by iloveeclipse** [comment]
Yes, but I'm not working on this plugin anymore because it cannot be used on 4.x Eclipse anymore due the breaking API changes in 4.x.
